### ISSUE TITLE
actions-runner-system namespace stuck on terminating

### ISSUE THREAD

**Issue by kaykhancheckpoint** [summerwind/actions-runner-controller#236]
Hi, the `actions-runner-system` namesapce seems to be stuck on terminating, after running the below command.

```
kubectl delete -f https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml
```

If i try to output all the resource on this namespace i get the following:

```
kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n actions-runner-system
```

> NAME                                                      ORGANIZATION   REPOSITORY   LABELS   STATUS
runner.actions.summerwind.dev/github-runner-2dflt-lq4n9   CheckpointGG                         Running

I tried deleting this resource manually but it does not want to go away. ```kubectl -n actions-runner-system delete runner.actions.summerwind.dev/github-runner-2dflt-lq4n9```

Any ideas?

**Comment by igorbrigadir** [comment]
This worked for me in a much older version, not sure if its the same for you: https://github.com/summerwind/actions-runner-controller/issues/141#issuecomment-715393210

**Comment by kaykhancheckpoint** [comment]
I eventually fixed this using https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-408599873, Although it could leave you with ghost resources, i went with it anyway because i had exhausted other options.

After the above, I `apply` then `delete` then `apply` again and it works. The reason i had to delete and apply again was because of some ghost resources that were not deleted properly during termination.

**Comment by onedr0p** [comment]
FWIW this issue should be re-opened and examined by the authors of the software as to why this is happening. So many people are running into this issue.

**Comment by mumoshu** [comment]
@onedr0p Hey! TD;DR; Please feel free to reopen and post more details of this problem. This is more or less an open-source project.

As the primary maintainer, I'd try my best to fix the issue in my spare time. Strictly speaking, no one's paying for me to fix issues so I'm perhaps I have a right to not compelled to give user-support like, a paid software, right?

That being said, I'll help to investigate anyone's issues out of my- kindness? (I don't really know why I'm working hard maintaining various opensource projects without getting paid) It happens especially when the one who reported the issue is a long-time contributor to the project. But I believe that it doesn't mean I'll always investigate issues for everyone.

Hope this helps.
