### ISSUE TITLE
Runner CR recreates automatically

### ISSUE THREAD

**Issue by vterdunov** [summerwind/actions-runner-controller#424]
Hi

Namespace: actions-runner-system

Problem: Custom Resource (runner.actions.summerwind.dev/example-runner-deployment-8lfjt-98qm8) recreates even after it has been "properly" removed and namespace recreated.

What i did:
- namespace in Terminating status.
- Runner CR (actions.summerwind.dev/v1alpha1 Runner) <--- this will be recreated
```bash
k get runner -n actions-runner-system
NAME                                    ORGANIZATION   REPOSITORY          LABELS   STATUS
example-runner-deployment-8lfjt-98qm8                  vterdunov/actions            Running
```

- CRD stuck (cannot delete)
```bash
k get crd | grep summ
runners.actions.summerwind.dev
```

- patch CRD
```bash
k patch crd runners.actions.summerwind.dev -p '{"metadata":{"finalizers":[]}}' --type=merge
```

As result the namespace was deleted, however if i install the CRD again the Runner CR (example-runner-deployment-8lfjt-98qm8) will be created automatically. E.g.:

- Install CRD
```bash
k apply -f https://raw.githubusercontent.com/summerwind/actions-runner-controller/master/charts/actions-runner-controller/crds/actions.summerwind.dev_runners.yaml
customresourcedefinition.apiextensions.k8s.io/runners.actions.summerwind.dev created
```

```bash
k get crd | grep summ
runners.actions.summerwind.dev                       2021-03-26T14:22:32Z
```

- The Runner CR is back:
```bash
k get runner -A
NAMESPACE               NAME                                    ENTERPRISE   ORGANIZATION   REPOSITORY          LABELS   STATUS
actions-runner-system   example-runner-deployment-8lfjt-98qm8                               vterdunov/actions            Running
```

**Comment by vterdunov** [comment]
Hmm for some reason the CR can be deleted. previously it didn't work.
```bash
k -n actions-runner-system patch runner.actions.summerwind.dev example-runner-deployment-8lfjt-98qm8 -p '{"metadata":{"finalizers":[]}}' --type=merge
`

**Comment by mumoshu** [comment]
@vterdunov Thanks for sharing! It wasn't clear from your logs, but you probably had to somehow set deletionTimestamp on runners before emptying finalizers. (I think you'd usually need to run `kubectl delete runner example-runner-deployment-8lfjt-98qm8` before the `kubectl patch` for that).  Otherwise, actions-runner-controller would reload the finalizers like any other K8s controllers and that could result in runners not being deleted.

Also if your runners are ones originally created by a RunnerDeployment, just deleting the RunnerDeployment should do the job.
