### ISSUE TITLE
Getting started - runner connection refused

### ISSUE THREAD

**Issue by jeffrey-kinesso** [summerwind/actions-runner-controller#78]
Hello,
I really appreciate all the <3 that is going into auto-scaling self hosted runners.
I am closely following the readme and running into:
```
➜  summerwind kubectl apply -f runner.yaml
Error from server (InternalError): error when creating "runner.yaml": Internal error occurred: failed calling webhook "mutate.runner.actions.summerwind.dev": Post https://webhook-service.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runner?timeout=30s: dial tcp 10.105.1.87:443: connect: connection refused
```

- I'm using k8s for Mac locally
- I've tried standing up the cert-manager stuff using both kubectl and helm

Any thoughts would really be appreciated!  thank you

**Comment by mumoshu** [comment]
@jeffrey-kinesso Hey! AFAKI this error is usually observed when your admission webhook service isn't working, or it's just not ready yet.

In the case of actions-runner-contorller, the admission webhook is served by the controller itself. So - Could you verify if the actions-runner-controller has one or more pods that are ready? If not, `kubectl describe pod` and `kubectl logs --previous` on the actions-runner-controller pod(s) may help investigating the root cause.

Please also note that if you tried to apply `runner.yaml` immediately after the actions-runner-controller is deployed, it may fail like that, too. This is due to that the controller is not yet ready. You can just retry applying `runner.yaml`.

**Comment by jeffrey-kinesso** [comment]
@mumoshu - thank you so much Kuoka!  I'll give this a try and follow up

**Comment by jeffrey-kinesso** [comment]
Update - No longer an issue for me!  Maybe fixed in recent version... more likely user error :)
